In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
## Define the Vocabulary Size
voc_size = 10000

In [21]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]

one_hot_repr

[[6564, 2309, 334, 852],
 [6564, 2309, 334, 4056],
 [6564, 4878, 334, 7594],
 [4401, 2429, 8687, 8714, 6287],
 [4401, 2429, 8687, 8714, 75],
 [3123, 6564, 438, 334, 6117],
 [4618, 3137, 801, 8714]]

In [22]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 6564 2309  334  852]
 [   0    0    0    0 6564 2309  334 4056]
 [   0    0    0    0 6564 4878  334 7594]
 [   0    0    0 4401 2429 8687 8714 6287]
 [   0    0    0 4401 2429 8687 8714   75]
 [   0    0    0 3123 6564  438  334 6117]
 [   0    0    0    0 4618 3137  801 8714]]


In [24]:
## feature representation
dim = 10

In [30]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')

In [31]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [ 0.03246261, -0.0433809 , -0.03094285, -0.0265985 ,
          0.02252321,  0.01656611, -0.0438496 , -0.01460817,
         -0.04224266,  0.03636852],
        [-0.03488705,  0.02818687, -0.01743933, -0.0184955 ,
          0.00653731, -0.04925912, -0.00469729,  0.0250406 ,
          0.02874556, -0.00171846],
        [-0.03927107,  0.00995474, -0.01270274, -0.0

In [33]:
embedded_docs[0]

array([   0,    0,    0,    0, 6564, 2309,  334,  852], dtype=int32)

In [37]:
import numpy as np

x = np.array([embedded_docs[0]])   # (1, sent_length)
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [-0.01635033,  0.03202264, -0.00628127, -0.01917038,
         -0.0400689 , -0.01991657,  0.00795554,  0.02513912,
         -0.01485201,  0.01685769],
        [ 0.03246261, -0.0433809 , -0.03094285, -0.0265985 ,
          0.02252321,  0.01656611, -0.0438496 , -0.01460817,
         -0.04224266,  0.03636852],
        [-0.03488705,  0.02818687, -0.01743933, -0.0184955 ,
          0.00653731, -0.04925912, -0.00469729,  0.0250406 ,
          0.02874556, -0.00171846],
        [-0.03927107,  0.00995474, -0.01270274, -0.0